title: Aussie Clean Services
email: contact@aussieclean.com
baseurl: "/cleaningservice"
url: "https://codandn.github.io"
markdown: kramdown
theme: null

# Custom variables
brand_color: "#2A9D8F"
