- title: Home Cleaning
  description: Complete residential cleaning service
  icon: https://img.icons8.com/ios-filled/100/2A9D8F/clean.png

- title: Office Cleaning
  description: Commercial cleaning solutions
  icon: https://img.icons8.com/ios-filled/100/2A9D8F/office.png

- title: Deep Cleaning
  description: Thorough intensive cleaning service
  icon: https://img.icons8.com/ios-filled/100/2A9D8F/cleaning.png
